name: Integration Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: integration-test

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: csye7125
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: postgres
          POSTGRES_SCHEMA: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: npm install
        run: npm install

      - name: Configure environment variables
        run: |
          echo "PORT=8080" > .env
          echo "DB_USERNAME=csye7125" >> .env
          echo "DB_PASSWORD=mysecretpassword" >> .env
          echo "DB_HOSTNAME=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DBNAME=postgres" >> .env
          echo "DB_SCHEMA=app" >> .env

      - name: test
        run: npm run test
