name: Integration Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: integration-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: npm install
        run: npm install

      - name: Setup Database
        run: |
          sudo apt install mariadb-server
          sudo mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';FLUSH PRIVILEGES;"
          sudo mysql -uroot -ppassword -e "CREATE DATABASE IF NOT EXISTS csye7125;"
          echo "PORT=8080" > .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env
          echo "DB_HOSTNAME=localhost" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DBNAME=csye7125" >> .env

      - name: test
        run: npm run test
